services:
  web:
    image: php:8.3-fpm
    container_name: php-app
    volumes:
      - ./app:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "9093:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web